baseURL: 'https://www.sullecose.it/'
languageCode: 'it-IT'
defaultContentLanguage: it
title: 'Sulle Cose'
enableGitInfo: true
enableRobotsTXT: true
Params:
  author:
    display_name: "ğŸ™ Io"
  iso8601: 2006-01-02T15:04:05-07:00
  og_type: article
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.8
markup:
  goldmark:
    renderer:
      unsafe: true
disableKinds:
  - taxonomy
  - term
